/**
 * ============================================================
 *  GYMBATTLE — ARSENAL: 100 ARMAS NOVAS
 * ============================================================
 * 25 armas para cada caminho (Força, Destreza, Inteligência e Fé), com
 * vários tipos em cada um: quem sobe Fé também encontra foices, espadas,
 * lanças e machados — não só selos. O segundo requisito (ex.: Destreza
 * numa foice de Fé) é pequeno e só existe pelo tipo da arma.
 *
 * Por caminho: 5 comuns, 6 incomuns, 6 raras, 5 épicas e 3 lendárias.
 */
import type { WeaponDef } from './types.js';
import { group } from './weaponKit.js';

// ====================================================================
// FORÇA
// ====================================================================
const forca: WeaponDef[] = [
  ...group('sword', [
    {
      id: 'espada-larga-do-ferreiro', name: 'Espada Larga do Ferreiro', rarity: 'common', price: 330,
      req: { str: 12 }, scale: { str: 'C' },
      lore: 'O ferreiro a fez para testar a bigorna. A bigorna perdeu.',
      a1: ['Corte largo', 'Dois cortes pesados e diretos.', 'combo', 'slash', { hits: 2 }],
      a2: ['Ombrada', 'Investe com o ombro e corta de cima.', 'dash', 'heavy_slash', { range: 105 }],
      look: { blade: '#b8bcc4', handle: '#4a3020' },
    },
    {
      id: 'espada-bastarda-do-leao', name: 'Espada Bastarda do Leão', rarity: 'rare', price: 2150,
      req: { str: 19, dex: 10 }, scale: { str: 'B', dex: 'D' },
      lore: 'O pomo tem a juba de um leão. O dono, a juba de quem não pula treino de perna.',
      a1: ['Rugido de aço', 'Três cortes com o peso do corpo.', 'combo', 'multi_slash', { hits: 3 }],
      a2: ['Bote do leão', 'Salto curto e corte vertical que atordoa.', 'leap', 'heavy_slash', { power: 2, range: 130, status: { type: 'shock', chance: 0.3, duration: 700 } }],
      look: { blade: '#d8d2c0', handle: '#8a5a1a', glow: '#f5b544' },
    },
    {
      id: 'espada-do-deus-da-guerra', name: 'Espada do Deus da Guerra', rarity: 'legendary', price: 11300,
      req: { str: 36, vig: 20 }, scale: { str: 'S', vig: 'D' }, el: 'fire',
      lore: 'Dizem que foi forjada no primeiro campo de batalha, com o calor do primeiro grito.',
      a1: ['Fúria marcial', 'Três cortes em chamas.', 'combo', 'multi_slash', { hits: 3, power: 1.15, status: { type: 'burn', chance: 0.3, duration: 3000 } }],
      a2: ['Brado da guerra', 'Crava a espada e ergue uma parede de fogo.', 'area', 'flame_wave', { power: 2.4, range: 230, shake: 0.6 }],
      look: { blade: '#e8c8a0', handle: '#5a1a10', glow: '#ff7a2f' },
    },
  ]),
  ...group('greatsword', [
    {
      id: 'montante-da-fronteira', name: 'Montante da Fronteira', rarity: 'uncommon', price: 930,
      req: { str: 15, fort: 10 }, scale: { str: 'B' },
      lore: 'Guardou sozinho uma ponte por três invernos. A ponte caiu; o montante não.',
      a1: ['Talho da fronteira', 'Golpe horizontal pesado.', 'melee', 'heavy_slash'],
      a2: ['Marco de pedra', 'Crava o montante no chão e solta uma onda de choque.', 'area', 'shockwave', { range: 170, shake: 0.4 }],
      look: { blade: '#9aa0a8', handle: '#3a2a1a' },
    },
    {
      id: 'espadao-do-rei-montanha', name: 'Espadão do Rei da Montanha', rarity: 'epic', price: 5300,
      req: { str: 27, fort: 16 }, scale: { str: 'A', fort: 'D' },
      lore: 'Tão pesado que o rei só o levantava uma vez por dia. Uma vez bastava.',
      a1: ['Avalanche', 'Golpe esmagador com tremor.', 'melee', 'heavy_slash', { power: 1.1, shake: 0.35 }],
      a2: ['Deslizamento', 'Salta e cai com o espadão, rachando a arena.', 'leap', 'quake', { power: 2.3, range: 220, shake: 0.7, status: { type: 'launch', chance: 1, duration: 600 } }],
      look: { blade: '#7a8088', handle: '#2a2018', glow: '#c9a24a' },
    },
    {
      id: 'espadao-quebra-mundos', name: 'Espadão Quebra-Mundos', rarity: 'legendary', price: 11900,
      req: { str: 38, fort: 22 }, scale: { str: 'S', fort: 'C' },
      lore: 'Não tem fio. Não precisa ter.',
      a1: ['Fim da linha', 'Golpe colossal que faz a tela tremer.', 'melee', 'heavy_slash', { power: 1.25, shake: 0.5 }],
      a2: ['Quebra-mundos', 'Gira e explode o chão em volta, lançando o inimigo.', 'area', 'quake', { power: 2.6, range: 240, shake: 1, status: { type: 'launch', chance: 1, duration: 750 } }],
      look: { blade: '#4a4e56', handle: '#1a1410', glow: '#ff5a2a' },
    },
  ]),
  ...group('katana', [
    {
      id: 'odachi-de-ferro-bruto', name: 'Odachi de Ferro Bruto', rarity: 'uncommon', price: 860,
      req: { str: 14, dex: 10 }, scale: { str: 'B', dex: 'D' },
      lore: 'Uma katana para quem acha katana leve demais.',
      a1: ['Corte pesado', 'Corte longo e firme.', 'melee', 'heavy_slash', { range: 90 }],
      a2: ['Raiz partida', 'Avança e corta de baixo para cima, lançando o alvo.', 'dash', 'uppercut', { range: 140, status: { type: 'launch', chance: 1, duration: 500 } }],
      look: { blade: '#a8acb4', handle: '#2a1a1a' },
    },
    {
      id: 'katana-do-oni', name: 'Katana do Oni', rarity: 'epic', price: 4900,
      req: { str: 25, dex: 14 }, scale: { str: 'A', dex: 'D' }, el: 'fire',
      lore: 'Arrancada da mão de um demônio de chifres. Ele ainda quer de volta.',
      a1: ['Fúria do oni', 'Dois cortes brutais em brasa.', 'combo', 'heavy_slash', { hits: 2, status: { type: 'burn', chance: 0.3, duration: 3000 } }],
      a2: ['Chifrada infernal', 'Investida que explode em chamas ao acertar.', 'dash', 'black_flame', { power: 2.2, range: 180, shake: 0.5 }],
      look: { blade: '#c0302a', handle: '#1a0a0a', glow: '#ff7a2f' },
    },
  ]),
  ...group('dagger', [
    {
      id: 'cutelos-do-carniceiro', name: 'Cutelos Gêmeos do Carniceiro', rarity: 'uncommon', price: 740,
      req: { str: 13, dex: 8 }, scale: { str: 'B' },
      lore: 'Dois cutelos, zero delicadeza.',
      a1: ['Picadinho', 'Quatro golpes pesados alternados.', 'combo', 'multi_slash', { hits: 4, status: { type: 'bleed', chance: 0.25, duration: 3000 } }],
      a2: ['Arremesso de cutelo', 'Arremessa um cutelo girando.', 'projectile', 'dagger_throw', { range: 260, power: 1.5 }],
      look: { blade: '#c0c4ca', handle: '#5a2a1a' },
    },
    {
      id: 'adaga-espada-do-ogro', name: 'Adaga-Espada do Ogro', rarity: 'rare', price: 1950,
      req: { str: 19, fort: 10 }, scale: { str: 'B', fort: 'D' },
      lore: 'Para o ogro era uma adaguinha. Para você é uma espada de respeito.',
      a1: ['Estocadas do ogro', 'Três estocadas que empurram forte.', 'combo', 'multi_slash', { hits: 3, knockback: 7 }],
      a2: ['Cabeçada', 'Avança e acerta com o cabo, atordoando.', 'dash', 'uppercut', { range: 130, status: { type: 'shock', chance: 0.5, duration: 800 } }],
      look: { blade: '#8a8e96', handle: '#4a3a2a' },
    },
  ]),
  ...group('axe', [
    {
      id: 'machado-de-pedreira', name: 'Machado de Pedreira', rarity: 'common', price: 290,
      req: { str: 11, fort: 8 }, scale: { str: 'C' },
      lore: 'Quebrava pedra antes de quebrar escudos.',
      a1: ['Pancada lateral', 'Golpe diagonal pesado.', 'melee', 'heavy_slash'],
      a2: ['Rachar a rocha', 'Golpe no chão com onda curta.', 'area', 'shockwave', { range: 140 }],
      look: { blade: '#8a8e94', handle: '#5a3a1a' },
    },
    {
      id: 'machado-duplo-do-vale', name: 'Machado Duplo do Vale', rarity: 'uncommon', price: 900,
      req: { str: 15, fort: 9 }, scale: { str: 'B' },
      lore: 'Duas lâminas: uma para ir, outra para voltar.',
      a1: ['Vai e volta', 'Dois golpes em sequência.', 'combo', 'heavy_slash', { hits: 2 }],
      a2: ['Redemoinho do vale', 'Gira acertando várias vezes.', 'area', 'whirlwind', { range: 110, hits: 3 }],
      look: { blade: '#a0a4aa', handle: '#3a2a1a' },
    },
    {
      id: 'machado-dos-mil-invernos', name: 'Machado dos Mil Invernos', rarity: 'rare', price: 2250,
      req: { str: 20, fort: 12 }, scale: { str: 'B', int: 'D' }, el: 'ice',
      lore: 'Encontrado dentro de um bloco de gelo. O dono ainda estava junto.',
      a1: ['Golpe gélido', 'Golpe pesado que pode congelar.', 'melee', 'heavy_slash', { status: { type: 'freeze', chance: 0.15, duration: 600 } }],
      a2: ['Machado arremessado', 'Arremessa o machado coberto de gelo.', 'projectile', 'ice_shard', { power: 1.9, range: 320, mana: 6 }],
      look: { blade: '#b8e0f0', handle: '#2a3a4a', glow: '#7fd6ff' },
    },
    {
      id: 'machado-carrasco-do-abismo', name: 'Machado-Carrasco do Abismo', rarity: 'epic', price: 5100,
      req: { str: 26, vig: 14 }, scale: { str: 'A', vig: 'D' }, el: 'shadow',
      lore: 'Serviu ao carrasco de um reino que caiu no abismo. Ninguém sabe quem caiu primeiro.',
      a1: ['Sentença sombria', 'Dois golpes pesados com rastro de sombra.', 'combo', 'heavy_slash', { hits: 2, lifesteal: 0.1 }],
      a2: ['Queda no abismo', 'Salta e cai com o machado, abrindo chamas negras.', 'leap', 'black_flame', { power: 2.3, range: 230, shake: 0.6 }],
      look: { blade: '#2a2238', handle: '#140e1a', glow: '#8b5cf6' },
    },
  ]),
  ...group('hammer', [
    {
      id: 'clava-de-carvalho', name: 'Clava de Carvalho', rarity: 'common', price: 270,
      req: { str: 12 }, scale: { str: 'C' },
      lore: 'Um galho grosso com ambição.',
      a1: ['Bordoada', 'Golpe esmagador.', 'melee', 'heavy_slash'],
      a2: ['Bordoada dupla', 'Dois golpes seguidos de cima.', 'combo', 'shockwave', { hits: 2 }],
      look: { blade: '#6a4a2a', handle: '#4a3018' },
    },
    {
      id: 'martelo-de-cerco', name: 'Martelo de Cerco', rarity: 'uncommon', price: 960,
      req: { str: 16, fort: 10 }, scale: { str: 'B' },
      lore: 'Derrubava portões. Hoje derruba recordes de supino.',
      a1: ['Aríete', 'Golpe frontal que empurra muito.', 'melee', 'heavy_slash', { knockback: 17 }],
      a2: ['Muralha abaixo', 'Salta e esmaga o chão.', 'leap', 'leap_slam', { power: 2, range: 200, shake: 0.5 }],
      look: { blade: '#7a7e86', handle: '#3a2a1a' },
    },
    {
      id: 'maca-estrela-da-tempestade', name: 'Maça-Estrela da Tempestade', rarity: 'rare', price: 2350,
      req: { str: 19, fai: 9 }, scale: { str: 'B', fai: 'D' }, el: 'lightning',
      lore: 'As pontas atraem raios. O dono aprendeu a gostar disso.',
      a1: ['Pancada elétrica', 'Golpe que pode paralisar.', 'melee', 'heavy_slash', { status: { type: 'shock', chance: 0.25, duration: 900 } }],
      a2: ['Chamar o trovão', 'Bate no chão e três raios caem à sua volta.', 'area', 'lightning_storm', { power: 2, hits: 3, mana: 8, range: 170, shake: 0.4 }],
      look: { blade: '#8a90a0', handle: '#2a2a3a', glow: '#ffe24a' },
    },
    {
      id: 'maca-do-sol-nascente', name: 'Maça do Sol Nascente', rarity: 'legendary', price: 11100,
      req: { str: 36, fai: 16 }, scale: { str: 'S', fai: 'D' }, el: 'fire',
      lore: 'Brilha ao amanhecer, como quem treina às 5 da manhã.',
      a1: ['Aurora', 'Golpe flamejante com tremor.', 'melee', 'heavy_slash', { power: 1.25, shake: 0.4, status: { type: 'burn', chance: 0.35, duration: 3000 } }],
      a2: ['Sol a pino', 'Ergue a maça e um sol explode sobre o alvo.', 'area', 'meteor', { power: 2.6, mana: 10, shake: 0.8 }],
      look: { blade: '#e8b040', handle: '#5a2a10', glow: '#ffd24a' },
    },
  ]),
  ...group('spear', [
    {
      id: 'lanca-de-caca-ao-javali', name: 'Lança de Caça ao Javali', rarity: 'common', price: 300,
      req: { str: 11, dex: 8 }, scale: { str: 'C', dex: 'D' },
      lore: 'Tem uma trava para o javali não subir pela lança. Funciona com gente também.',
      a1: ['Estocada firme', 'Estocada longa e pesada.', 'melee', 'thrust'],
      a2: ['Carga do caçador', 'Corre com a lança baixa.', 'dash', 'thrust', { range: 170 }],
      look: { blade: '#b0b4ba', handle: '#6a4a2a' },
    },
    {
      id: 'alabarda-do-carrasco', name: 'Alabarda do Carrasco', rarity: 'rare', price: 2200,
      req: { str: 20, dex: 9 }, scale: { str: 'B', dex: 'D' },
      lore: 'Metade lança, metade machado, inteira problema.',
      a1: ['Varrida pesada', 'Golpe em arco com a lâmina de machado.', 'melee', 'heavy_slash', { range: 118 }],
      a2: ['Gancho do carrasco', 'Puxa o inimigo e corta.', 'pull', 'chain_pull', { power: 1.9, range: 200 }],
      look: { blade: '#9a9ea6', handle: '#2a1a14' },
    },
    {
      id: 'lanca-dos-titas', name: 'Lança dos Titãs', rarity: 'epic', price: 5000,
      req: { str: 24, fort: 14 }, scale: { str: 'A', fort: 'D' },
      lore: 'Três homens para carregar, um titã para usar. Ou você, depois de muito treino.',
      a1: ['Estocada titânica', 'Duas estocadas que empurram muito.', 'combo', 'thrust', { hits: 2, knockback: 10 }],
      a2: ['Queda do titã', 'Salta e crava a lança no chão com onda de choque.', 'leap', 'shockwave', { power: 2.2, range: 240, shake: 0.6 }],
      look: { blade: '#8a8e96', handle: '#3a2a1a', glow: '#c9a24a' },
    },
  ]),
  ...group('scythe', [
    {
      id: 'foice-de-guerra', name: 'Foice de Guerra', rarity: 'uncommon', price: 880,
      req: { str: 14, dex: 9 }, scale: { str: 'B', dex: 'D' },
      lore: 'Lâmina de foice, cabo de lança, humor de sargento.',
      a1: ['Ceifa pesada', 'Golpe em arco que empurra.', 'melee', 'heavy_slash', { knockback: 12 }],
      a2: ['Moinho', 'Gira a foice acertando duas vezes.', 'area', 'spin', { range: 115, hits: 2 }],
      look: { blade: '#9aa0a6', handle: '#4a3020' },
    },
    {
      id: 'foice-do-ceifador-de-montanhas', name: 'Foice do Ceifador de Montanhas', rarity: 'epic', price: 4800,
      req: { str: 25, dex: 12 }, scale: { str: 'A', dex: 'D' },
      lore: 'Colhia pedras como quem colhe trigo.',
      a1: ['Colheita de pedra', 'Dois giros pesados.', 'combo', 'heavy_slash', { hits: 2, range: 110 }],
      a2: ['Deslizar da encosta', 'Avança girando e lança o inimigo.', 'dash', 'whirlwind', { power: 2.1, range: 190, status: { type: 'launch', chance: 1, duration: 600 } }],
      look: { blade: '#6a6e76', handle: '#2a2018', glow: '#c9814a' },
    },
  ]),
  ...group('bow', [
    {
      id: 'arco-longo-de-teixo', name: 'Arco Longo de Teixo', rarity: 'common', price: 310,
      req: { str: 11, dex: 8 }, scale: { str: 'C', dex: 'D' },
      lore: 'Precisa de braço para puxar. Não de mira: de braço.',
      a1: ['Flecha pesada', 'Flecha lenta que empurra.', 'projectile', 'arrow', { power: 1.1, knockback: 7 }],
      a2: ['Tiro tenso', 'Flecha perfurante com força total.', 'projectile', 'piercing_arrow', { power: 2 }],
      look: { blade: '#8a5a2a', handle: '#4a3018' },
    },
    {
      id: 'besta-de-cerco', name: 'Besta de Cerco', rarity: 'rare', price: 2300,
      req: { str: 18, dex: 12 }, scale: { str: 'B', dex: 'D' },
      lore: 'Foi feita para derrubar torres. Ninguém avisou que era portátil.',
      a1: ['Virote de cerco', 'Virote pesado e lento.', 'projectile', 'piercing_arrow', { power: 1.25, knockback: 9 }],
      a2: ['Salva', 'Três virotes seguidos.', 'projectile', 'arrow', { hits: 3, power: 2 }],
      look: { blade: '#5a4a3a', handle: '#2a2018' },
    },
  ]),
];

// ====================================================================
// DESTREZA
// ====================================================================
const destreza: WeaponDef[] = [
  ...group('sword', [
    {
      id: 'rapieira-do-duelista', name: 'Rapieira do Duelista', rarity: 'common', price: 320,
      req: { dex: 14 }, scale: { dex: 'C' },
      lore: 'Fina como um fio de cabelo, rápida como uma desculpa para faltar no treino.',
      a1: ['Estocadas rápidas', 'Três estocadas curtas.', 'combo', 'thrust', { hits: 3 }],
      a2: ['Lunge', 'Avanço longo com estocada.', 'dash', 'thrust', { range: 150 }],
      look: { blade: '#dfe3ea', handle: '#8a6a2a' },
    },
    {
      id: 'sabre-do-corsario', name: 'Sabre do Corsário', rarity: 'uncommon', price: 790,
      req: { dex: 17 }, scale: { dex: 'B' },
      lore: 'Roubado de um almirante, que roubou de outro corsário. Tradição.',
      a1: ['Corte do convés', 'Dois cortes curvos.', 'combo', 'slash', { hits: 2 }],
      a2: ['Abordagem', 'Salta sobre o alvo com um corte.', 'leap', 'slash', { power: 1.9, range: 140 }],
      look: { blade: '#d0d4dc', handle: '#6a2a1a' },
    },
    {
      id: 'sabre-do-relampago-azul', name: 'Sabre do Relâmpago Azul', rarity: 'epic', price: 4700,
      req: { dex: 26, fai: 12 }, scale: { dex: 'A', fai: 'D' }, el: 'lightning',
      lore: 'Chega antes do trovão. O trovão sempre pede desculpas.',
      a1: ['Faísca tripla', 'Três cortes elétricos.', 'combo', 'multi_slash', { hits: 3, status: { type: 'shock', chance: 0.2, duration: 900 } }],
      a2: ['Raio azul', 'Atravessa o alvo como um raio.', 'dash', 'lightning_spear', { power: 2.1, range: 200, mana: 8 }],
      look: { blade: '#a8d0ff', handle: '#1a2a4a', glow: '#4aa8ff' },
    },
  ]),
  ...group('greatsword', [
    {
      id: 'espadao-curvo-do-deserto', name: 'Espadão Curvo do Deserto', rarity: 'rare', price: 2250,
      req: { dex: 21, str: 12 }, scale: { dex: 'B', str: 'D' },
      lore: 'Grande como um espadão, curvo como uma duna. Dança com o vento quente.',
      a1: ['Arco da duna', 'Corte largo e rápido para o tamanho.', 'melee', 'slash', { range: 100 }],
      a2: ['Tempestade de areia', 'Gira três vezes avançando.', 'dash', 'whirlwind', { hits: 3, power: 1.9, range: 170 }],
      look: { blade: '#e0d0a8', handle: '#6a4a1a' },
    },
    {
      id: 'espadao-da-danca-carmesim', name: 'Espadão da Dança Carmesim', rarity: 'legendary', price: 10700,
      req: { dex: 34, str: 18 }, scale: { dex: 'S', str: 'C' }, el: 'blood',
      lore: 'Pesado demais para dançar. A dançarina discordou e venceu.',
      a1: ['Passo carmesim', 'Dois cortes giratórios com sangramento.', 'combo', 'blood_slash', { hits: 2, power: 1.2, status: { type: 'bleed', chance: 0.4, duration: 3000 } }],
      a2: ['Valsa sangrenta', 'Avança girando e rouba vida.', 'dash', 'shadow_spin', { power: 2.4, range: 220, hits: 2, lifesteal: 0.2 }],
      look: { blade: '#b01e34', handle: '#2a0a10', glow: '#e0243b' },
    },
  ]),
  ...group('katana', [
    {
      id: 'wakizashi-do-aprendiz', name: 'Wakizashi do Aprendiz', rarity: 'common', price: 280,
      req: { dex: 13 }, scale: { dex: 'C' },
      lore: 'A lâmina curta que todo aprendiz carrega enquanto sonha com a longa.',
      a1: ['Corte curto', 'Dois cortes rápidos.', 'combo', 'slash', { hits: 2 }],
      a2: ['Saque veloz', 'Avança e corta ao sacar.', 'dash', 'slash', { range: 130 }],
      look: { blade: '#d8dce4', handle: '#2a2a3a' },
    },
    {
      id: 'katana-da-garca-branca', name: 'Katana da Garça Branca', rarity: 'rare', price: 2050,
      req: { dex: 23 }, scale: { dex: 'B' },
      lore: 'Espera parada num pé só. Depois não espera mais.',
      a1: ['Bico da garça', 'Iaijutsu preciso.', 'melee', 'slash', { power: 1.1 }],
      a2: ['Voo da garça', 'Corte que lança uma lâmina de ar.', 'projectile', 'crescent', { power: 1.9, range: 320 }],
      look: { blade: '#f0f4f8', handle: '#e0e0e8', glow: '#ffffff' },
    },
    {
      id: 'katana-da-flor-de-cerejeira', name: 'Katana da Flor de Cerejeira', rarity: 'epic', price: 4950,
      req: { dex: 27, vig: 12 }, scale: { dex: 'A', vig: 'D' }, el: 'blood',
      lore: 'As pétalas caem devagar. O inimigo, rápido.',
      a1: ['Pétalas', 'Três cortes que causam sangramento.', 'combo', 'blood_slash', { hits: 3, status: { type: 'bleed', chance: 0.35, duration: 3000 } }],
      a2: ['Hanami', 'Some e reaparece cortando.', 'dash', 'shadow_spin', { power: 2.2, range: 240 }],
      look: { blade: '#f0c0cc', handle: '#3a1a22', glow: '#ff8aa8' },
    },
    {
      id: 'katana-do-primeiro-sol', name: 'Katana do Primeiro Sol', rarity: 'legendary', price: 10400,
      req: { dex: 38, fort: 18 }, scale: { dex: 'S', fort: 'D' }, el: 'fire',
      lore: 'Forjada com a luz do primeiro amanhecer do mundo. Ainda está quente.',
      a1: ['Nascer do sol', 'Quatro cortes dourados que podem queimar.', 'combo', 'multi_slash', { hits: 4, power: 1.2, status: { type: 'burn', chance: 0.25, duration: 3000 } }],
      a2: ['Meio-dia', 'Corte que dispara uma meia-lua de fogo.', 'projectile', 'crescent', { power: 2.5, range: 380, hits: 2 }],
      look: { blade: '#ffe0a0', handle: '#5a2a10', glow: '#ffb03a' },
    },
  ]),
  ...group('dagger', [
    {
      id: 'kukri-do-batedor', name: 'Kukri do Batedor', rarity: 'common', price: 260,
      req: { dex: 13 }, scale: { dex: 'C' },
      lore: 'Abre trilha na mata e fecha discussões.',
      a1: ['Talhos curtos', 'Três cortes rápidos.', 'combo', 'multi_slash', { hits: 3 }],
      a2: ['Rasteira', 'Avança baixo e corta.', 'dash', 'slash', { range: 120 }],
      look: { blade: '#c8ccd2', handle: '#5a3a1a' },
    },
    {
      id: 'estiletes-do-assassino', name: 'Estiletes do Assassino', rarity: 'uncommon', price: 820,
      req: { dex: 18 }, scale: { dex: 'B' },
      lore: 'Tão finos que o alvo só percebe no dia seguinte.',
      a1: ['Pontadas', 'Cinco estocadas rápidas com sangramento.', 'combo', 'multi_slash', { hits: 5, status: { type: 'bleed', chance: 0.25, duration: 3000 } }],
      a2: ['Leque de agulhas', 'Arremessa dois estiletes.', 'projectile', 'dagger_throw', { hits: 2, range: 280, power: 1.4 }],
      look: { blade: '#e0e4ea', handle: '#1a1a1a' },
    },
    {
      id: 'adagas-de-vidro-negro', name: 'Adagas de Vidro Negro', rarity: 'rare', price: 2100,
      req: { dex: 22, int: 9 }, scale: { dex: 'B', int: 'D' }, el: 'shadow',
      lore: 'Vidro vulcânico lascado à mão. Corta até a sombra.',
      a1: ['Estilhaços', 'Quatro golpes sombrios.', 'combo', 'multi_slash', { hits: 4 }],
      a2: ['Passo na sombra', 'Some e golpeia pelas costas.', 'dash', 'shadow_spin', { power: 2, range: 230, mana: 6 }],
      look: { blade: '#2a2a34', handle: '#141418', glow: '#8b5cf6' },
    },
  ]),
  ...group('axe', [
    {
      id: 'machadinhas-gemeas', name: 'Machadinhas Gêmeas', rarity: 'uncommon', price: 850,
      req: { dex: 17, str: 9 }, scale: { dex: 'B', str: 'D' },
      lore: 'Leves para arremessar, pesadas para receber.',
      a1: ['Rodízio', 'Três golpes alternados.', 'combo', 'heavy_slash', { hits: 3 }],
      a2: ['Arremesso duplo', 'Lança as duas machadinhas girando.', 'projectile', 'dagger_throw', { hits: 2, range: 290 }],
      look: { blade: '#b0b4ba', handle: '#6a3a1a' },
    },
    {
      id: 'machados-do-furacao', name: 'Machados do Furacão', rarity: 'epic', price: 4850,
      req: { dex: 25, fort: 14 }, scale: { dex: 'A', fort: 'D' },
      lore: 'Quem gira com eles vira vento. Quem fica perto vira destroço.',
      a1: ['Rajada', 'Quatro golpes rápidos.', 'combo', 'multi_slash', { hits: 4 }],
      a2: ['Olho do furacão', 'Gira várias vezes puxando o ar.', 'area', 'whirlwind', { power: 2.2, range: 130, hits: 4, shake: 0.3 }],
      look: { blade: '#c8d0d8', handle: '#2a3a4a', glow: '#bfe8ff' },
    },
  ]),
  ...group('hammer', [
    {
      id: 'mangual-do-acrobata', name: 'Mangual do Acrobata', rarity: 'rare', price: 2150,
      req: { dex: 20, str: 10 }, scale: { dex: 'B', str: 'D' },
      lore: 'Uma bola de ferro numa corrente, girando mais rápido do que deveria.',
      a1: ['Chicotada', 'Dois giros da bola de ferro.', 'combo', 'heavy_slash', { hits: 2, range: 95 }],
      a2: ['Pêndulo', 'Gira o mangual acertando tudo em volta.', 'area', 'spin', { power: 1.9, range: 130, hits: 2 }],
      look: { blade: '#6a6e76', handle: '#3a2a1a' },
    },
  ]),
  ...group('spear', [
    {
      id: 'lanca-leve-do-cavaleiro', name: 'Lança Leve do Cavaleiro', rarity: 'uncommon', price: 810,
      req: { dex: 17, str: 8 }, scale: { dex: 'B' },
      lore: 'Feita para justas. Funciona melhor sem cavalo, dizem os cavalos.',
      a1: ['Estocada tripla', 'Três estocadas rápidas.', 'combo', 'thrust', { hits: 3 }],
      a2: ['Justa', 'Carga longa com a lança.', 'dash', 'thrust', { range: 190 }],
      look: { blade: '#d0d4da', handle: '#8a6a3a' },
    },
    {
      id: 'glaive-do-vento-norte', name: 'Glaive do Vento Norte', rarity: 'rare', price: 2200,
      req: { dex: 21, int: 9 }, scale: { dex: 'B', int: 'D' }, el: 'ice',
      lore: 'Assobia quando gira. Quem ouve sente frio.',
      a1: ['Corte do norte', 'Golpe em arco que pode congelar.', 'melee', 'slash', { range: 118, status: { type: 'freeze', chance: 0.15, duration: 600 } }],
      a2: ['Vento cortante', 'Dispara uma lâmina de vento gelado.', 'projectile', 'crescent', { power: 1.9, range: 330, mana: 6 }],
      look: { blade: '#c0e8f8', handle: '#2a3a4a', glow: '#7fd6ff' },
    },
    {
      id: 'lanca-do-cometa-errante', name: 'Lança do Cometa Errante', rarity: 'legendary', price: 10300,
      req: { dex: 36, vig: 18 }, scale: { dex: 'S', vig: 'D' }, el: 'arcane',
      lore: 'Caiu do céu numa noite sem lua. Ainda procura o caminho de volta.',
      a1: ['Cauda do cometa', 'Três estocadas com rastro azul.', 'combo', 'thrust', { hits: 3, power: 1.2 }],
      a2: ['Impacto do cometa', 'Salto altíssimo e mergulho com explosão.', 'leap', 'meteor', { power: 2.5, range: 280, shake: 0.7 }],
      look: { blade: '#a0c0ff', handle: '#1a2248', glow: '#5b8cff' },
    },
  ]),
  ...group('scythe', [
    {
      id: 'foice-curta-do-jardineiro', name: 'Foice Curta do Jardineiro', rarity: 'common', price: 290,
      req: { dex: 13, str: 8 }, scale: { dex: 'C' },
      lore: 'Poda roseiras e egos.',
      a1: ['Poda', 'Dois cortes curvos rápidos.', 'combo', 'slash', { hits: 2 }],
      a2: ['Canteiro', 'Gira a foice em volta do corpo.', 'area', 'spin', { range: 100 }],
      look: { blade: '#b8bcc4', handle: '#6a4a2a' },
    },
    {
      id: 'kamas-gemeas', name: 'Kamas Gêmeas', rarity: 'uncommon', price: 870,
      req: { dex: 18 }, scale: { dex: 'B' },
      lore: 'Duas foicinhas, quatro vezes mais problemas.',
      a1: ['Colheita dupla', 'Quatro cortes alternados.', 'combo', 'multi_slash', { hits: 4 }],
      a2: ['Corrente das kamas', 'Lança uma kama presa na corrente e puxa o alvo.', 'pull', 'chain_pull', { power: 1.8, range: 230 }],
      look: { blade: '#c8ccd4', handle: '#2a2a2a' },
    },
    {
      id: 'foice-danca-da-lamina', name: 'Foice da Dança da Lâmina', rarity: 'epic', price: 4750,
      req: { dex: 25, str: 12 }, scale: { dex: 'A', str: 'D' },
      lore: 'Quem a empunha nunca para de se mover. Nem na fila do supino.',
      a1: ['Rodopio', 'Giro amplo e rápido.', 'melee', 'shadow_spin', { range: 115, power: 1.1 }],
      a2: ['Ciclone de lâminas', 'Avança girando três vezes.', 'dash', 'whirlwind', { hits: 3, power: 2.1, range: 210 }],
      look: { blade: '#d8dce4', handle: '#3a1a2a', glow: '#ff8aa8' },
    },
  ]),
  ...group('bow', [
    {
      id: 'arco-de-bambu', name: 'Arco de Bambu', rarity: 'common', price: 250,
      req: { dex: 12 }, scale: { dex: 'C' },
      lore: 'Leve, flexível e barato. Como o primeiro par de tênis de academia.',
      a1: ['Flecha leve', 'Flecha rápida.', 'projectile', 'arrow'],
      a2: ['Par de flechas', 'Duas flechas quase juntas.', 'projectile', 'arrow', { hits: 2 }],
      look: { blade: '#c8b070', handle: '#6a5a2a' },
    },
    {
      id: 'arco-composto-da-estepe', name: 'Arco Composto da Estepe', rarity: 'uncommon', price: 880,
      req: { dex: 18 }, scale: { dex: 'B' },
      lore: 'Chifre, madeira e tendão. Atira longe, atira forte, atira de novo.',
      a1: ['Flecha da estepe', 'Flecha longa e precisa.', 'projectile', 'arrow', { power: 1.1 }],
      a2: ['Chuva da estepe', 'Flechas caem do alto sobre o alvo.', 'area', 'arrow_rain', { power: 1.9, hits: 4 }],
      look: { blade: '#8a6a3a', handle: '#3a2a1a' },
    },
    {
      id: 'arco-do-falcao-peregrino', name: 'Arco do Falcão Peregrino', rarity: 'rare', price: 2350,
      req: { dex: 24 }, scale: { dex: 'B' },
      lore: 'O falcão mergulha a 300 km/h. A flecha, um pouco mais.',
      a1: ['Mergulho', 'Flecha perfurante.', 'projectile', 'piercing_arrow', { power: 1.1 }],
      a2: ['Revoada', 'Quatro flechas em leque.', 'projectile', 'arrow', { hits: 4, power: 2 }],
      look: { blade: '#6a5040', handle: '#2a2018', glow: '#f5d08a' },
    },
    {
      id: 'arco-do-vendaval-eterno', name: 'Arco do Vendaval Eterno', rarity: 'epic', price: 5200,
      req: { dex: 28, fort: 12 }, scale: { dex: 'A', fort: 'D' }, el: 'lightning',
      lore: 'A corda é um fio de tempestade. Cada disparo é um trovão pequeno.',
      a1: ['Flecha-trovão', 'Flecha elétrica que pode paralisar.', 'projectile', 'lightning_spear', { status: { type: 'shock', chance: 0.2, duration: 900 } }],
      a2: ['Tempestade de flechas', 'Raios e flechas caem sobre o alvo.', 'area', 'lightning_storm', { power: 2.2, hits: 3, shake: 0.4 }],
      look: { blade: '#4a5a7a', handle: '#1a2030', glow: '#ffe24a' },
    },
  ]),
];

// ====================================================================
// INTELIGÊNCIA
// ====================================================================
const inteligencia: WeaponDef[] = [
  ...group('sword', [
    {
      id: 'espada-runica-do-escriba', name: 'Espada Rúnica do Escriba', rarity: 'common', price: 340,
      req: { int: 11, str: 8 }, scale: { int: 'C', str: 'D' }, el: 'arcane',
      lore: 'O escriba gravou nela todas as runas que sabia. Eram só três, mas funcionam.',
      a1: ['Corte rúnico', 'Dois cortes com runas azuis.', 'combo', 'slash', { hits: 2 }],
      a2: ['Runa disparada', 'Dispara uma runa de energia.', 'projectile', 'arcane_missiles', { power: 1.8, range: 300, mana: 8 }],
      look: { blade: '#b0c0e8', handle: '#2a2a4a', glow: '#5b8cff' },
    },
    {
      id: 'lamina-glacial-do-mago', name: 'Lâmina Glacial do Mago', rarity: 'uncommon', price: 840,
      req: { int: 14, dex: 8 }, scale: { int: 'B' }, el: 'ice',
      lore: 'O mago cansou de errar magias de longe e resolveu errar de perto.',
      a1: ['Fio gelado', 'Corte que pode congelar.', 'melee', 'slash', { status: { type: 'freeze', chance: 0.18, duration: 600 } }],
      a2: ['Estilhaço', 'Dispara um fragmento de gelo teleguiado.', 'projectile', 'ice_shard', { power: 1.8, range: 320, mana: 10 }],
      look: { blade: '#c8ecff', handle: '#2a3a5a', glow: '#7fd6ff' },
    },
    {
      id: 'espada-do-arquimago-guerreiro', name: 'Espada do Arquimago Guerreiro', rarity: 'epic', price: 5100,
      req: { int: 27, dex: 14 }, scale: { int: 'A', dex: 'D' }, el: 'arcane',
      lore: 'Para quem se recusou a escolher entre o grimório e o supino.',
      a1: ['Combo arcano', 'Três cortes com explosões de runas.', 'combo', 'multi_slash', { hits: 3 }],
      a2: ['Lâmina de mana', 'Avança como um feixe arcano.', 'dash', 'arcane_missiles', { power: 2.2, range: 220, mana: 12 }],
      look: { blade: '#a8b8ff', handle: '#1a1a3a', glow: '#5b8cff' },
    },
  ]),
  ...group('greatsword', [
    {
      id: 'espadao-da-geleira', name: 'Espadão da Geleira', rarity: 'rare', price: 2300,
      req: { int: 17, str: 14 }, scale: { int: 'B', str: 'D' }, el: 'ice',
      lore: 'Um pedaço de geleira que alguém teve a paciência de afiar.',
      a1: ['Avalanche gélida', 'Golpe pesado que pode congelar.', 'melee', 'heavy_slash', { status: { type: 'freeze', chance: 0.18, duration: 700 } }],
      a2: ['Prisão da geleira', 'Crava o espadão e o gelo prende o alvo.', 'area', 'ice_prison', { power: 1.9, range: 260, mana: 14, status: { type: 'freeze', chance: 0.7, duration: 700 } }],
      look: { blade: '#d0f0ff', handle: '#3a4a5a', glow: '#7fd6ff' },
    },
    {
      id: 'espadao-do-cometa-arcano', name: 'Espadão do Cometa Arcano', rarity: 'legendary', price: 11600,
      req: { int: 33, str: 18 }, scale: { int: 'S', str: 'C' }, el: 'arcane',
      lore: 'Um meteoro caiu na torre dos magos. Eles fizeram uma espada. Óbvio.',
      a1: ['Rastro estelar', 'Golpe pesado que explode em runas.', 'melee', 'heavy_slash', { power: 1.25, shake: 0.4 }],
      a2: ['Chamado do cometa', 'Ergue o espadão e um cometa cai sobre o alvo.', 'area', 'meteor', { power: 2.7, mana: 18, shake: 0.9 }],
      look: { blade: '#8aa0ff', handle: '#14143a', glow: '#b57cff' },
    },
  ]),
  ...group('katana', [
    {
      id: 'katana-do-espectro', name: 'Katana do Espectro', rarity: 'rare', price: 2150,
      req: { int: 18, dex: 12 }, scale: { int: 'B', dex: 'D' }, el: 'shadow',
      lore: 'O ferreiro morreu antes de terminar. Terminou depois.',
      a1: ['Corte fantasma', 'Corte com rastro de sombra.', 'melee', 'shadow_spin', { range: 90 }],
      a2: ['Lâmina espectral', 'Dispara uma meia-lua de sombra.', 'projectile', 'crescent', { power: 1.9, range: 340, mana: 12 }],
      look: { blade: '#4a4a6a', handle: '#1a1a2a', glow: '#8b5cf6' },
    },
    {
      id: 'katana-do-grimorio-proibido', name: 'Katana do Grimório Proibido', rarity: 'legendary', price: 10600,
      req: { int: 33, dex: 20 }, scale: { int: 'S', dex: 'C' }, el: 'shadow',
      lore: 'Cada página arrancada do grimório virou uma dobra do aço.',
      a1: ['Páginas cortantes', 'Quatro cortes sombrios.', 'combo', 'multi_slash', { hits: 4, power: 1.2 }],
      a2: ['Capítulo final', 'Abre um vórtice que puxa e corta o alvo.', 'pull', 'shadow_orb', { power: 2.5, range: 340, mana: 14, shake: 0.5 }],
      look: { blade: '#3a2a5a', handle: '#140a1e', glow: '#b57cff' },
    },
  ]),
  ...group('dagger', [
    {
      id: 'adaga-ritual-do-alquimista', name: 'Adaga Ritual do Alquimista', rarity: 'common', price: 280,
      req: { int: 10, dex: 8 }, scale: { int: 'C' }, el: 'poison',
      lore: 'Usada para cortar ervas. As ervas eram venenosas. A adaga lembra.',
      a1: ['Talhos tóxicos', 'Três golpes que podem envenenar.', 'combo', 'multi_slash', { hits: 3, status: { type: 'poison', chance: 0.3, duration: 4000 } }],
      a2: ['Frasco arremessado', 'Arremessa um frasco que vira nuvem tóxica.', 'projectile', 'poison_cloud', { power: 1.4, range: 240, mana: 6, status: { type: 'poison', chance: 0.4, duration: 4000 } }],
      look: { blade: '#b8d8a0', handle: '#3a2a1a', glow: '#7ddc3d' },
    },
    {
      id: 'adagas-da-mente-partida', name: 'Adagas da Mente Partida', rarity: 'rare', price: 2000,
      req: { int: 18, dex: 12 }, scale: { int: 'B', dex: 'D' }, el: 'arcane',
      lore: 'Cortam pensamentos. O alvo esquece até o próprio treino.',
      a1: ['Pensamentos cortados', 'Quatro golpes arcanos.', 'combo', 'multi_slash', { hits: 4 }],
      a2: ['Enxame mental', 'Três projéteis arcanos teleguiados.', 'projectile', 'arcane_missiles', { hits: 3, power: 1.9, range: 320, mana: 12 }],
      look: { blade: '#c0c8ff', handle: '#2a2a4a', glow: '#5b8cff' },
    },
  ]),
  ...group('axe', [
    {
      id: 'machado-do-necromante', name: 'Machado do Necromante', rarity: 'uncommon', price: 900,
      req: { int: 15, str: 9 }, scale: { int: 'B', str: 'D' }, el: 'shadow',
      lore: 'Corta a carne e depois conversa com ela.',
      a1: ['Golpe funesto', 'Golpe pesado que rouba um pouco de vida.', 'melee', 'heavy_slash', { lifesteal: 0.15 }],
      a2: ['Orbe da cova', 'Dispara um orbe sombrio lento.', 'projectile', 'shadow_orb', { power: 1.9, range: 320, mana: 10 }],
      look: { blade: '#3a3a4a', handle: '#1a141e', glow: '#8b5cf6' },
    },
  ]),
  ...group('hammer', [
    {
      id: 'martelo-do-arquiteto-runico', name: 'Martelo do Arquiteto Rúnico', rarity: 'rare', price: 2400,
      req: { int: 18, str: 12 }, scale: { int: 'B', str: 'D' }, el: 'arcane',
      lore: 'Construiu torres de magos com três marteladas. A quarta derrubou uma.',
      a1: ['Pedra fundamental', 'Golpe pesado que explode em runas.', 'melee', 'heavy_slash'],
      a2: ['Fundação arcana', 'Bate no chão e ergue runas explosivas.', 'area', 'shockwave', { power: 2, range: 220, mana: 12, shake: 0.5 }],
      look: { blade: '#6a78b0', handle: '#2a2a3a', glow: '#5b8cff' },
    },
  ]),
  ...group('spear', [
    {
      id: 'lanca-de-mana', name: 'Lança de Mana', rarity: 'uncommon', price: 860,
      req: { int: 14, dex: 9 }, scale: { int: 'B' }, el: 'arcane',
      lore: 'Metade cabo, metade feitiço. A parte do feitiço é a que machuca.',
      a1: ['Estocadas arcanas', 'Duas estocadas com brilho azul.', 'combo', 'thrust', { hits: 2 }],
      a2: ['Lança de energia', 'Dispara uma lança de mana.', 'projectile', 'lightning_spear', { power: 1.8, range: 340, mana: 10 }],
      look: { blade: '#a0b8ff', handle: '#3a3a5a', glow: '#5b8cff' },
    },
    {
      id: 'lanca-do-inverno-eterno', name: 'Lança do Inverno Eterno', rarity: 'epic', price: 4900,
      req: { int: 25, dex: 12 }, scale: { int: 'A', dex: 'D' }, el: 'ice',
      lore: 'Onde ela toca, a primavera desiste.',
      a1: ['Pontas de gelo', 'Três estocadas que podem congelar.', 'combo', 'thrust', { hits: 3, status: { type: 'freeze', chance: 0.12, duration: 600 } }],
      a2: ['Inverno sem fim', 'Salta e crava a lança, prendendo o alvo no gelo.', 'leap', 'ice_prison', { power: 2.2, range: 250, mana: 14, status: { type: 'freeze', chance: 0.6, duration: 800 } }],
      look: { blade: '#d8f4ff', handle: '#2a3a5a', glow: '#7fd6ff' },
    },
  ]),
  ...group('scythe', [
    {
      id: 'foice-de-osso', name: 'Foice de Osso', rarity: 'common', price: 300,
      req: { int: 10, dex: 8 }, scale: { int: 'C' }, el: 'shadow',
      lore: 'Feita de um osso grande demais para ser de alguém conhecido.',
      a1: ['Ceifa óssea', 'Golpe em arco com sombra.', 'melee', 'slash', { range: 100 }],
      a2: ['Mão da cova', 'Uma mão sombria puxa o alvo.', 'pull', 'chain_pull', { range: 230, mana: 8 }],
      look: { blade: '#e0dccc', handle: '#4a4034', glow: '#8b5cf6' },
    },
    {
      id: 'foice-do-lich', name: 'Foice do Lich', rarity: 'rare', price: 2250,
      req: { int: 19, dex: 10 }, scale: { int: 'B', dex: 'D' }, el: 'ice',
      lore: 'O lich guardou a alma num filactério. A foice guarda as dos outros.',
      a1: ['Toque do lich', 'Giro gelado que pode congelar.', 'melee', 'shadow_spin', { range: 110, status: { type: 'freeze', chance: 0.15, duration: 600 } }],
      a2: ['Nevasca da cripta', 'Estilhaços de gelo caem sobre o alvo.', 'area', 'lightning_storm', { power: 2, hits: 3, mana: 14 }],
      look: { blade: '#b0d8f0', handle: '#2a2a3a', glow: '#7fd6ff' },
    },
    {
      id: 'foice-do-pesadelo', name: 'Foice do Pesadelo', rarity: 'epic', price: 4850,
      req: { int: 27, dex: 13 }, scale: { int: 'A', dex: 'D' }, el: 'shadow',
      lore: 'Quem sonha com ela acorda cansado. Quem apanha dela não acorda.',
      a1: ['Sonho ruim', 'Dois giros sombrios que roubam vida.', 'combo', 'shadow_spin', { hits: 2, range: 110, lifesteal: 0.12 }],
      a2: ['Pesadelo', 'Arremessa uma lua negra giratória.', 'projectile', 'crescent', { power: 2.2, range: 360, hits: 2, mana: 14 }],
      look: { blade: '#2a1a3a', handle: '#140a1a', glow: '#b57cff' },
    },
  ]),
  ...group('bow', [
    {
      id: 'arco-de-cristal', name: 'Arco de Cristal', rarity: 'uncommon', price: 890,
      req: { int: 14, dex: 10 }, scale: { int: 'B', dex: 'D' }, el: 'arcane',
      lore: 'A corda é um raio de luz presa entre dois cristais.',
      a1: ['Flecha de luz', 'Flecha arcana teleguiada.', 'projectile', 'arcane_missiles'],
      a2: ['Leque prismático', 'Três flechas de luz.', 'projectile', 'arcane_missiles', { hits: 3, mana: 8 }],
      look: { blade: '#c0d8ff', handle: '#4a5a8a', glow: '#5b8cff' },
    },
    {
      id: 'arco-do-vazio', name: 'Arco do Vazio', rarity: 'epic', price: 5000,
      req: { int: 26, dex: 14 }, scale: { int: 'A', dex: 'D' }, el: 'shadow',
      lore: 'Atira pedaços de nada. O nada dói bastante.',
      a1: ['Flecha do vazio', 'Orbe sombrio disparado como flecha.', 'projectile', 'shadow_orb', { power: 1.1 }],
      a2: ['Chuva do vazio', 'Flechas negras caem sobre o alvo.', 'area', 'arrow_rain', { power: 2.2, hits: 5, mana: 12 }],
      look: { blade: '#2a2440', handle: '#14101e', glow: '#8b5cf6' },
    },
  ]),
  ...group('staff', [
    {
      id: 'cajado-de-salgueiro', name: 'Cajado de Salgueiro', rarity: 'common', price: 260,
      req: { int: 10, ess: 8 }, scale: { int: 'C' }, el: 'ice',
      lore: 'Salgueiro chora; o cajado faz os outros chorarem.',
      a1: ['Gota gelada', 'Pequeno fragmento de gelo.', 'projectile', 'ice_shard'],
      a2: ['Garoa gelada', 'Estilhaços caem sobre o alvo.', 'area', 'lightning_storm', { hits: 2 }],
      look: { blade: '#8a9a6a', handle: '#5a4a2a', glow: '#7fd6ff' },
    },
    {
      id: 'orbe-do-astronomo', name: 'Orbe do Astrônomo', rarity: 'common', price: 350,
      req: { int: 11, ess: 8 }, scale: { int: 'C' }, el: 'arcane',
      lore: 'Mostra as estrelas. Às vezes arremessa uma.',
      a1: ['Estrela cadente', 'Projétil arcano rápido.', 'projectile', 'arcane_missiles', { power: 1.05 }],
      a2: ['Constelação', 'Quatro pequenas estrelas teleguiadas.', 'projectile', 'arcane_missiles', { hits: 4 }],
      look: { blade: '#3a3a6a', handle: '#2a2a3a', glow: '#b57cff' },
    },
    {
      id: 'cajado-do-relampago-cativo', name: 'Cajado do Relâmpago Cativo', rarity: 'uncommon', price: 950,
      req: { int: 15, ess: 10 }, scale: { int: 'B' }, el: 'lightning',
      lore: 'Um raio preso num cristal, muito irritado com isso.',
      a1: ['Faísca', 'Lança de raio curta que pode paralisar.', 'projectile', 'lightning_spear', { status: { type: 'shock', chance: 0.2, duration: 800 } }],
      a2: ['Libertar o raio', 'Três raios caem sobre o alvo.', 'area', 'lightning_storm', { power: 1.9, hits: 3 }],
      look: { blade: '#5a5a7a', handle: '#2a2a3a', glow: '#ffe24a' },
    },
    {
      id: 'cajado-da-lua-crescente', name: 'Cajado da Lua Crescente', rarity: 'uncommon', price: 990,
      req: { int: 16, ess: 11 }, scale: { int: 'B' }, el: 'ice',
      lore: 'Fica mais forte à noite. O dono também, com a pré-treino.',
      a1: ['Luar', 'Meia-lua de luz fria.', 'projectile', 'crescent'],
      a2: ['Maré lunar', 'Prisão de gelo sobre o alvo.', 'area', 'ice_prison', { power: 1.7, status: { type: 'freeze', chance: 0.7, duration: 700 } }],
      look: { blade: '#c0d0f0', handle: '#3a4a6a', glow: '#bfe8ff' },
    },
    {
      id: 'cajado-do-eclipse-solar', name: 'Cajado do Eclipse Solar', rarity: 'rare', price: 2400,
      req: { int: 19, ess: 14 }, scale: { int: 'B', ess: 'D' }, el: 'fire',
      lore: 'Guarda o sol atrás de uma lua de pedra. Às vezes deixa escapar um pouco.',
      a1: ['Coroa solar', 'Bola de fogo que pode queimar.', 'projectile', 'fireball', { status: { type: 'burn', chance: 0.35, duration: 3000 } }],
      a2: ['Eclipse', 'O sol escondido explode sobre o alvo.', 'area', 'meteor', { power: 2, shake: 0.5 }],
      look: { blade: '#2a2020', handle: '#4a2a1a', glow: '#ff7a2f' },
    },
    {
      id: 'cajado-da-tempestade-negra', name: 'Cajado da Tempestade Negra', rarity: 'epic', price: 5300,
      req: { int: 28, ess: 18 }, scale: { int: 'A', ess: 'D' }, el: 'lightning',
      lore: 'Uma nuvem de chuva presa numa gaiola de ferro. Troveja quando está com fome.',
      a1: ['Raio negro', 'Lança de raio que pode paralisar.', 'projectile', 'lightning_spear', { power: 1.1, status: { type: 'shock', chance: 0.25, duration: 900 } }],
      a2: ['Tempestade negra', 'Quatro raios em área com flash.', 'area', 'lightning_storm', { power: 2.3, hits: 4, shake: 0.6 }],
      look: { blade: '#2a2a3a', handle: '#141418', glow: '#ffe24a' },
    },
    {
      id: 'cajado-da-singularidade', name: 'Cajado da Singularidade', rarity: 'legendary', price: 11700,
      req: { int: 35, ess: 26 }, scale: { int: 'S', ess: 'C' }, el: 'shadow',
      lore: 'No topo, um ponto tão denso que a luz faz fila para entrar.',
      a1: ['Gravidade', 'Três orbes sombrios que puxam levemente.', 'projectile', 'shadow_orb', { hits: 3, power: 1.2 }],
      a2: ['Horizonte de eventos', 'Um buraco negro engole e esmaga o alvo.', 'pull', 'shadow_orb', { power: 2.8, range: 380, shake: 0.9 }],
      look: { blade: '#140e20', handle: '#2a2238', glow: '#b57cff' },
    },
  ]),
];

// ====================================================================
// FÉ
// ====================================================================
const fe: WeaponDef[] = [
  ...group('sword', [
    {
      id: 'espada-do-escudeiro-devoto', name: 'Espada do Escudeiro Devoto', rarity: 'common', price: 330,
      req: { fai: 10, str: 8 }, scale: { fai: 'C', str: 'D' }, el: 'holy',
      lore: 'O escudeiro reza antes de cada golpe. São golpes bem rezados.',
      a1: ['Corte devoto', 'Dois cortes com brilho dourado.', 'combo', 'slash', { hits: 2 }],
      a2: ['Prece curta', 'Estocada que libera um pulso sagrado.', 'dash', 'holy_nova', { range: 110, mana: 8 }],
      look: { blade: '#e8e4d0', handle: '#8a6a2a', glow: '#ffd86b' },
    },
    {
      id: 'espada-do-paladino', name: 'Espada do Paladino', rarity: 'rare', price: 2300,
      req: { fai: 17, str: 12 }, scale: { fai: 'B', str: 'D' }, el: 'holy',
      lore: 'Jurou proteger os fracos. Os fortes ficaram por conta própria.',
      a1: ['Juramento', 'Três cortes sagrados.', 'combo', 'multi_slash', { hits: 3 }],
      a2: ['Luz do juramento', 'Ergue a espada: cura e explode em luz ao redor.', 'heal', 'holy_nova', { power: 1.4, range: 120, stamina: 24, mana: 12 }],
      look: { blade: '#f0ecd8', handle: '#c9a24a', glow: '#ffd86b' },
    },
    {
      id: 'espada-da-aurora-sangrenta', name: 'Espada da Aurora Sangrenta', rarity: 'epic', price: 4900,
      req: { fai: 25, dex: 13 }, scale: { fai: 'A', dex: 'D' }, el: 'blood',
      lore: 'A ordem dos cavaleiros de sangue reza com o próprio sangue. É um culto difícil.',
      a1: ['Sangria sagrada', 'Três cortes que roubam vida.', 'combo', 'blood_slash', { hits: 3, lifesteal: 0.12 }],
      a2: ['Aurora rubra', 'Corte que dispara uma meia-lua de sangue.', 'projectile', 'crescent', { power: 2.1, range: 340, mana: 12, status: { type: 'bleed', chance: 0.5, duration: 3000 } }],
      look: { blade: '#e0a0a8', handle: '#4a1018', glow: '#e0243b' },
    },
  ]),
  ...group('greatsword', [
    {
      id: 'espadao-da-catedral', name: 'Espadão da Catedral', rarity: 'rare', price: 2450,
      req: { fai: 18, str: 14 }, scale: { fai: 'B', str: 'D' }, el: 'holy',
      lore: 'Ficava pendurado no altar. Um dia desceu sozinho para trabalhar.',
      a1: ['Sino da catedral', 'Golpe pesado que ressoa.', 'melee', 'heavy_slash', { knockback: 15 }],
      a2: ['Vitral partido', 'Crava o espadão e um pilar de luz desce sobre o alvo.', 'area', 'holy_beam', { power: 2, range: 240, mana: 14, shake: 0.4 }],
      look: { blade: '#f0e8c8', handle: '#6a4a1a', glow: '#ffd86b' },
    },
    {
      id: 'espadao-do-julgamento-solar', name: 'Espadão do Julgamento Solar', rarity: 'legendary', price: 11800,
      req: { fai: 36, str: 20 }, scale: { fai: 'S', str: 'C' }, el: 'fire',
      lore: 'O sol escolhe um campeão por era. Este espadão foi o recado.',
      a1: ['Veredito solar', 'Golpe flamejante com tremor.', 'melee', 'heavy_slash', { power: 1.25, shake: 0.4, status: { type: 'burn', chance: 0.35, duration: 3000 } }],
      a2: ['Julgamento', 'Salta e cai como um sol, incendiando a arena.', 'leap', 'meteor', { power: 2.6, range: 260, mana: 14, shake: 0.9 }],
      look: { blade: '#ffe0a0', handle: '#5a2a10', glow: '#ff9a2a' },
    },
  ]),
  ...group('katana', [
    {
      id: 'katana-do-monge-trovao', name: 'Katana do Monge do Trovão', rarity: 'uncommon', price: 890,
      req: { fai: 15, dex: 10 }, scale: { fai: 'B', dex: 'D' }, el: 'lightning',
      lore: 'O monge meditou sob uma tempestade por um ano. A katana absorveu tudo.',
      a1: ['Corte do trovão', 'Corte que pode paralisar.', 'melee', 'slash', { status: { type: 'shock', chance: 0.25, duration: 800 } }],
      a2: ['Relâmpago sagrado', 'Dispara uma lança de raio.', 'projectile', 'lightning_spear', { power: 1.8, range: 340, mana: 10 }],
      look: { blade: '#e8e8f0', handle: '#3a2a4a', glow: '#ffe24a' },
    },
    {
      id: 'katana-do-sol-da-manha', name: 'Katana do Sol da Manhã', rarity: 'epic', price: 5000,
      req: { fai: 27, dex: 14 }, scale: { fai: 'A', dex: 'D' }, el: 'holy',
      lore: 'Brilha mais forte a cada manhã em que o dono vai treinar.',
      a1: ['Primeira luz', 'Três cortes dourados.', 'combo', 'multi_slash', { hits: 3 }],
      a2: ['Raiar', 'Avança como um raio de sol e explode em luz.', 'dash', 'holy_nova', { power: 2.2, range: 220, mana: 12 }],
      look: { blade: '#fff0c0', handle: '#8a6a2a', glow: '#ffd86b' },
    },
  ]),
  ...group('dagger', [
    {
      id: 'adaga-do-confessor', name: 'Adaga do Confessor', rarity: 'uncommon', price: 770,
      req: { fai: 13, dex: 9 }, scale: { fai: 'B' }, el: 'holy',
      lore: 'Ouve todos os pecados. Castiga só alguns.',
      a1: ['Penitências', 'Quatro golpes com brilho sagrado.', 'combo', 'multi_slash', { hits: 4 }],
      a2: ['Absolvição', 'Arremessa a adaga envolta em luz.', 'projectile', 'holy_beam', { power: 1.8, range: 320, mana: 8 }],
      look: { blade: '#f0e8d0', handle: '#4a3a2a', glow: '#ffd86b' },
    },
    {
      id: 'punhais-do-sacrilegio', name: 'Punhais do Sacrilégio', rarity: 'rare', price: 2050,
      req: { fai: 18, dex: 12 }, scale: { fai: 'B', dex: 'D' }, el: 'blood',
      lore: 'Roubados de um altar proibido. O altar ainda os chama à noite.',
      a1: ['Rito profano', 'Cinco golpes que causam sangramento.', 'combo', 'blood_slash', { hits: 5, status: { type: 'bleed', chance: 0.3, duration: 3000 } }],
      a2: ['Oferenda', 'Avança e drena vida do alvo.', 'dash', 'blood_slash', { power: 1.9, range: 200, mana: 8, lifesteal: 0.35 }],
      look: { blade: '#c8a0a8', handle: '#2a0a10', glow: '#e0243b' },
    },
  ]),
  ...group('axe', [
    {
      id: 'machado-do-cruzado', name: 'Machado do Cruzado', rarity: 'uncommon', price: 910,
      req: { fai: 14, str: 10 }, scale: { fai: 'B', str: 'D' }, el: 'fire',
      lore: 'Atravessou o deserto em chamas. Ficou com o gosto pelo fogo.',
      a1: ['Golpe fervoroso', 'Golpe pesado que pode queimar.', 'melee', 'heavy_slash', { status: { type: 'burn', chance: 0.3, duration: 3000 } }],
      a2: ['Brasa sagrada', 'Golpe no chão que solta uma onda de fogo.', 'area', 'flame_wave', { power: 1.8, range: 240, mana: 10 }],
      look: { blade: '#d8c8a8', handle: '#6a2a10', glow: '#ff7a2f' },
    },
    {
      id: 'machado-do-inquisidor-escarlate', name: 'Machado do Inquisidor Escarlate', rarity: 'epic', price: 5200,
      req: { fai: 26, str: 14 }, scale: { fai: 'A', str: 'D' }, el: 'fire',
      lore: 'Faz perguntas com a lâmina. Ninguém gosta das respostas.',
      a1: ['Interrogatório', 'Dois golpes em chamas.', 'combo', 'heavy_slash', { hits: 2, status: { type: 'burn', chance: 0.3, duration: 3000 } }],
      a2: ['Fogueira', 'Crava o machado e uma fogueira explode à sua volta.', 'area', 'flame_wave', { power: 2.2, mana: 14, range: 190, shake: 0.6, status: { type: 'burn', chance: 0.6, duration: 3000 } }],
      look: { blade: '#b83020', handle: '#2a0a0a', glow: '#ff7a2f' },
    },
  ]),
  ...group('hammer', [
    {
      id: 'maca-do-capelao', name: 'Maça do Capelão', rarity: 'common', price: 340,
      req: { fai: 11, str: 8 }, scale: { fai: 'C', str: 'D' }, el: 'holy',
      lore: 'O capelão prega a paz. A maça, o resto.',
      a1: ['Sermão', 'Golpe sagrado esmagador.', 'melee', 'heavy_slash'],
      a2: ['Bênção pesada', 'Bate no chão e ergue um pulso de luz.', 'area', 'holy_nova', { range: 150, mana: 8 }],
      look: { blade: '#d8d0b0', handle: '#5a4a2a', glow: '#ffd86b' },
    },
    {
      id: 'maca-do-martir', name: 'Maça do Mártir', rarity: 'uncommon', price: 980,
      req: { fai: 16, vig: 10 }, scale: { fai: 'B', vig: 'D' }, el: 'blood',
      lore: 'O mártir sangrou por todos. A maça cobra a conta.',
      a1: ['Sacrifício', 'Golpe que rouba vida.', 'melee', 'heavy_slash', { lifesteal: 0.2 }],
      a2: ['Martírio', 'Salta e esmaga o chão, drenando vida.', 'leap', 'blood_slash', { power: 1.9, range: 200, mana: 8, lifesteal: 0.25 }],
      look: { blade: '#8a3a40', handle: '#3a1a1a', glow: '#e0243b' },
    },
    {
      id: 'martelo-do-arcanjo', name: 'Martelo do Arcanjo', rarity: 'epic', price: 5400,
      req: { fai: 28, str: 16 }, scale: { fai: 'A', str: 'D' }, el: 'lightning',
      lore: 'Caiu do céu no meio de uma briga. Terminou a briga.',
      a1: ['Martelada celeste', 'Golpe que pode paralisar.', 'melee', 'heavy_slash', { power: 1.1, status: { type: 'shock', chance: 0.3, duration: 900 } }],
      a2: ['Ira do arcanjo', 'Bate no chão e raios caem à sua volta.', 'area', 'lightning_storm', { power: 2.3, hits: 4, mana: 14, range: 200, shake: 0.7 }],
      look: { blade: '#e0e4f0', handle: '#8a7a3a', glow: '#ffe24a' },
    },
  ]),
  ...group('spear', [
    {
      id: 'lanca-do-peregrino-do-sol', name: 'Lança do Peregrino do Sol', rarity: 'common', price: 310,
      req: { fai: 10, dex: 8 }, scale: { fai: 'C', dex: 'D' }, el: 'holy',
      lore: 'Levada em procissão por mil quilômetros. A ponta nunca perdeu o brilho.',
      a1: ['Estocadas da procissão', 'Duas estocadas sagradas.', 'combo', 'thrust', { hits: 2 }],
      a2: ['Raio da procissão', 'Dispara um raio de luz pela ponta.', 'projectile', 'holy_beam', { range: 340, mana: 8 }],
      look: { blade: '#f0e0b0', handle: '#8a6a3a', glow: '#ffd86b' },
    },
    {
      id: 'lanca-do-serafim', name: 'Lança do Serafim', rarity: 'rare', price: 2250,
      req: { fai: 19, dex: 10 }, scale: { fai: 'B', dex: 'D' }, el: 'fire',
      lore: 'Seis asas de fogo gravadas no cabo. Queimam só quem merece.',
      a1: ['Asa de fogo', 'Estocada longa que pode queimar.', 'melee', 'thrust', { range: 120, status: { type: 'burn', chance: 0.3, duration: 3000 } }],
      a2: ['Mergulho do serafim', 'Salta e mergulha em chamas.', 'leap', 'flame_wave', { power: 2, range: 240, mana: 12, shake: 0.5 }],
      look: { blade: '#ffd0a0', handle: '#8a4a1a', glow: '#ff7a2f' },
    },
    {
      id: 'lanca-do-trovao-divino', name: 'Lança do Trovão Divino', rarity: 'legendary', price: 10900,
      req: { fai: 36, vig: 18 }, scale: { fai: 'S', vig: 'D' }, el: 'lightning',
      lore: 'Quando o céu quer punir alguém pessoalmente, empresta esta lança.',
      a1: ['Descarga divina', 'Três estocadas elétricas.', 'combo', 'thrust', { hits: 3, power: 1.2, status: { type: 'shock', chance: 0.2, duration: 900 } }],
      a2: ['Trovão divino', 'Arremessa a lança como um raio gigante.', 'projectile', 'lightning_spear', { power: 2.6, range: 420, mana: 16, shake: 0.7 }],
      look: { blade: '#fff8c0', handle: '#4a4a6a', glow: '#ffe24a' },
    },
  ]),
  ...group('scythe', [
    {
      id: 'foice-da-colheita-santa', name: 'Foice da Colheita Santa', rarity: 'common', price: 320,
      req: { fai: 10, dex: 8 }, scale: { fai: 'C' }, el: 'holy',
      lore: 'Abençoada para colher o trigo da festa. Colhe outras coisas também.',
      a1: ['Colheita', 'Golpe em arco com brilho dourado.', 'melee', 'slash', { range: 100 }],
      a2: ['Feixe bendito', 'Gira a foice espalhando luz.', 'area', 'spin', { range: 120, mana: 6 }],
      look: { blade: '#f0e4c0', handle: '#8a6a2a', glow: '#ffd86b' },
    },
    {
      id: 'foice-da-ultima-prece', name: 'Foice da Última Prece', rarity: 'rare', price: 2200,
      req: { fai: 18, dex: 10 }, scale: { fai: 'B', dex: 'D' }, el: 'holy',
      lore: 'A última coisa que muitos ouviram foi uma oração. A dela.',
      a1: ['Prece cortante', 'Dois giros sagrados.', 'combo', 'slash', { hits: 2, range: 105 }],
      a2: ['Amém', 'Uma corrente de luz puxa o alvo para a lâmina.', 'pull', 'chain_pull', { power: 1.9, range: 280, mana: 12 }],
      look: { blade: '#fff0d0', handle: '#6a5a3a', glow: '#ffd86b' },
    },
    {
      id: 'foice-do-anjo-caido', name: 'Foice do Anjo Caído', rarity: 'legendary', price: 11400,
      req: { fai: 38, dex: 15 }, scale: { fai: 'S', dex: 'D' }, el: 'holy',
      lore: 'O anjo caiu, mas não soltou a foice. Agora colhe dos dois lados.',
      a1: ['Asas partidas', 'Dois giros amplos de luz que curam um pouco.', 'combo', 'shadow_spin', { hits: 2, power: 1.2, range: 120, lifesteal: 0.1 }],
      a2: ['Queda do anjo', 'Um pilar de luz colossal cai sobre o alvo.', 'area', 'holy_beam', { power: 2.7, mana: 16, shake: 0.9 }],
      look: { blade: '#fffae0', handle: '#3a3040', glow: '#ffd86b' },
    },
  ]),
  ...group('bow', [
    {
      id: 'arco-da-penitencia', name: 'Arco da Penitência', rarity: 'uncommon', price: 870,
      req: { fai: 14, dex: 10 }, scale: { fai: 'B', dex: 'D' }, el: 'holy',
      lore: 'Cada flecha é uma penitência. O alvo cumpre.',
      a1: ['Flecha penitente', 'Flecha de luz.', 'projectile', 'holy_beam'],
      a2: ['Chuva de graça', 'Flechas de luz caem sobre o alvo.', 'area', 'arrow_rain', { power: 1.9, hits: 4, mana: 8 }],
      look: { blade: '#e8d8a8', handle: '#6a4a2a', glow: '#ffd86b' },
    },
  ]),
  ...group('seal', [
    {
      id: 'talisma-da-vela-votiva', name: 'Talismã da Vela Votiva', rarity: 'common', price: 280,
      req: { fai: 10, ess: 8 }, scale: { fai: 'C' }, el: 'fire',
      lore: 'Uma vela que nunca apaga. Nem quando deveria.',
      a1: ['Pavio', 'Pequena bola de fogo sagrado.', 'projectile', 'fireball', { status: { type: 'burn', chance: 0.25, duration: 3000 } }],
      a2: ['Chama votiva', 'Cura um pouco com calor sagrado.', 'heal', 'heal', { power: 1.0, range: 0 }],
      look: { blade: '#f0d8a0', handle: '#8a5a2a', glow: '#ff9a3a' },
    },
    {
      id: 'selo-do-relampago-fiel', name: 'Selo do Relâmpago Fiel', rarity: 'uncommon', price: 940,
      req: { fai: 15, ess: 10 }, scale: { fai: 'B' }, el: 'lightning',
      lore: 'Os fiéis rezam por chuva. Este selo manda o raio junto.',
      a1: ['Raio fiel', 'Lança de raio.', 'projectile', 'lightning_spear'],
      a2: ['Tempestade devota', 'Três raios caem sobre o alvo.', 'area', 'lightning_storm', { power: 1.9, hits: 3 }],
      look: { blade: '#e0e0a0', handle: '#4a4a6a', glow: '#ffe24a' },
    },
    {
      id: 'selo-da-chama-purificadora', name: 'Selo da Chama Purificadora', rarity: 'rare', price: 2350,
      req: { fai: 19, ess: 14 }, scale: { fai: 'B', ess: 'D' }, el: 'fire',
      lore: 'Queima o mal. E a sobrancelha de quem estiver perto.',
      a1: ['Purificar', 'Labareda sagrada à frente.', 'area', 'flame_wave', { range: 180, status: { type: 'burn', chance: 0.35, duration: 3000 } }],
      a2: ['Pira', 'Uma coluna de fogo sobe sob o alvo.', 'area', 'meteor', { power: 2, shake: 0.5 }],
      look: { blade: '#ffc080', handle: '#6a3a1a', glow: '#ff7a2f' },
    },
    {
      id: 'selo-do-coro-celestial', name: 'Selo do Coro Celestial', rarity: 'epic', price: 5300,
      req: { fai: 28, ess: 18 }, scale: { fai: 'A', ess: 'D' }, el: 'holy',
      lore: 'Quando brilha, dá para ouvir o coro. Ninguém sabe cantar junto.',
      a1: ['Hino', 'Dois raios de luz em sequência.', 'projectile', 'holy_beam', { hits: 2, power: 1.1 }],
      a2: ['Aleluia', 'Pilar de luz sobre o alvo e cura para você.', 'area', 'holy_nova', { power: 2.3, mana: 38, shake: 0.6 }],
      look: { blade: '#fff4d0', handle: '#c9a24a', glow: '#ffd86b' },
    },
  ]),
];

export const ARSENAL: WeaponDef[] = [...forca, ...destreza, ...inteligencia, ...fe];
